---
name: Build -> Packages for Windows & MacOS
# yamllint disable-line rule:line-length

on:
  workflow_dispatch:

# set the run-name 
run-name: ${{ github.ref_name }} -> Build Packages (
  ${{ github.run_attempt }}
  )


jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                cd src/ &&
                pyinstaller podshell.spec &&
                pyinstaller podshell-console.spec &&
                cd dist/ &&
                zip -r9 podshell-macos *
            OUT_FILE_NAME: podshell-macos.zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
                cd src/ &&
                pyinstaller podshell.spec &&
                pyinstaller podshell-console.spec &&
                cd dist && 
                tar -acvf podshell-windows.zip podshell-console.exe podshell.exe
            OUT_FILE_NAME: podshell-windows.zip
    permissions:
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.0
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt
        pip install pyinstaller
        pip install Pillow

    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}

    - name: Archive artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ matrix.OUT_FILE_NAME }}
        path: src/dist/${{ matrix.OUT_FILE_NAME }}
