---
name: Lint-> super-linter (all codebase)

on:
  workflow_dispatch:
  
  schedule:
    # run once a month on the first day of the month at 00:00 UTC
    - cron: '0 0 1 * *'

# set the run-name 
run-name: ${{ github.ref_name }} -> Super-linter (all codebase) (
  ${{ github.run_attempt }}
  )

jobs:
  lint-all-codebase:

    name: Lint all codebase
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:

      - name: Get current date and time
        id: datetime
        run: |
          datetime=$(date +'%Y-%m-%dT%H-%M-%SZ')
          echo "datetime=$datetime" >> $GITHUB_OUTPUT

      - name: Display date/time in output (forensics when triaging issues)
        run: echo ${{ steps.datetime.outputs.datetime }}

      - name: Checkout Code
        uses: actions/checkout@v3.6.0
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH_EXEC: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PYTHON_ISORT: false
          FILTER_REGEX_EXCLUDE: ".github/workflows/.*"